-- ============================================================
-- 00_setup.sql  — Database, warehouse, roles, and stage setup
-- Run once as ACCOUNTADMIN or SYSADMIN
-- ============================================================

USE ROLE SYSADMIN;

-- Database & schemas
CREATE DATABASE IF NOT EXISTS SAN_JAC_DEMO;
CREATE SCHEMA IF NOT EXISTS SAN_JAC_DEMO.CORTEX;
CREATE SCHEMA IF NOT EXISTS SAN_JAC_DEMO.ANALYTICS;

-- Warehouse (XS for demo)
CREATE WAREHOUSE IF NOT EXISTS SAN_JAC_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE;

-- Stage for source documents (Cortex Search)
CREATE STAGE IF NOT EXISTS SAN_JAC_DEMO.CORTEX.DOCS_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- Stage for semantic model YAMLs (Cortex Analyst)
CREATE STAGE IF NOT EXISTS SAN_JAC_DEMO.CORTEX.ANALYST_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

GRANT USAGE ON DATABASE SAN_JAC_DEMO TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA SAN_JAC_DEMO.CORTEX TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA SAN_JAC_DEMO.ANALYTICS TO ROLE PUBLIC;
GRANT USAGE ON WAREHOUSE SAN_JAC_WH TO ROLE PUBLIC;
